Settings:
  Debug: false
  DesertDropRate: 1
  OutsideDropRate: 0.15
  AnnounceWishFulfillmentToEveryone: false
  BlacklistedWorlds:
    - WorldName
Customization:
  CommandWishes:
    - /home {playername} | I wish to get home, I wish to be safe
    - /broadcast example | I want an example
  Wishes:
    DefaultWish: false