Settings:
  Debug: false
  DesertDropRate: 1
  OutsideDropRate: 0.15
  AnnounceWishFulfillmentToEveryone: false
  BlacklistedWorlds:
    - WorldName
Customization:
  CommandWishes:
    - /home {playername} | I wish to get home, I wish to be safe
    - /broadcast example | I want an example
  Wishes:
    DefaultWish: false
  Unsafe_entities:
    - AREA_EFFECT_CLOUD
    - ARMOR_STAND
    - ARROW
    - DRAGON_FIREBALL
    - DROPPED_ITEM
    - EGG
    - ELDER_GUARDIAN
    - ENDER_PEARL
    - ENDER_SIGNAL
    - ENDER_DRAGON
    - EVOKER_FANGS
    - EXPERIENCE_ORB
    - FALLING_BLOCK
    - FIREBALL
    - FIREWORK
    - FISHING_HOOK
    - GIANT
    - ITEM_FRAME
    - LEASH_HITCH
    - LIGHTNING
    - LLAMA_SPIT
    - MINECART
    - MINECART_CHEST
    - MINECART_COMMAND
    - MINECART_FURNACE
    - MINECART_HOPPER
    - MINECART_MOB_SPAWNER
    - MINECART_TNT
    - PAINTING
    - PLAYER
    - PRIMED_TNT
    - SHULKER_BULLET
    - SMALL_FIREBALL
    - SNOWBALL
    - SPECTRAL_ARROW
    - SPLASH_POTION
    - THROWN_EXP_BOTTLE
    - TRIDENT
    - WANDERING_TRADER
    - UNKNOWN
    - WITHER
    - WITHER_SKULL
  Unsafe_potion_effects:
    - WITHER
    - HARM
    - HEAL
  Unsafe_materials:
    - AIR
    - ATTACHED_MELON_STEM
    - ATTACHED_PUMPKIN_STEM
    - BAMBOO
    - BARRIER
    - BEDROCK
    - BEE_NEST
    - BEETROOTS
    - BUBBLE_COLUMN
    - CAVE_AIR
    - CHAIN_COMMAND_BLOCK
    - COMMAND_BLOCK
    - COMMAND_BLOCK_MINECART
    - DEBUG_STICK
    - ELDER_GUARDIAN_SPAWN_EGG
    - END_GATEWAY
    - END_PORTAL
    - END_PORTAL_FRAME
    - FILLED_MAP
    - FIREWORK_ROCKET
    - FIREWORK_STAR
    - KNOWLEDGE_BOOK
    - MAP
    - MELON_STEM
    - PUMPKIN_STEM
    - SPECTRAL_ARROW
    - STRUCTURE_BLOCK
    - STRUCTURE_VOID