Settings:
  Debug: false
  DesertDropRate: 1
  OutsideDropRate: 0.15
  AnnounceWishFulfillmentToEveryone: false
  BlacklistedWorlds:
    - WorldName
Customization:
  CommandWishes:
    - /home {playername} | I wish to get home, I wish to be safe
    - /broadcast example | I want an example
  Wishes:
    DefaultWish: false
  Unsafe_entities:
    - AREA_EFFECT_CLOUD
    - ARMOR_STAND
    - COMPLEX_PART
    - DRAGON_FIREBALL
    - DROPPED_ITEM
    - EGG
    - ENDER_PEARL
    - ENDER_SIGNAL
    - EXPERIENCE_ORB
    - FALLING_BLOCK
    - FIREBALL
    - FIREWORK
    - FISHING_HOOK
    - EVOKER_FANGS
    - ITEM_FRAME
    - LEASH_HITCH
    - LIGHTNING
    - LINGERING_POTION
    - LLAMA_SPIT
    - MINECART
    - MINECART_CHEST
    - MINECART_COMMAND
    - MINECART_FURNACE
    - MINECART_HOPPER
    - MINECART_MOB_SPAWNER
    - MINECART_TNT
    - PAINTING
    - PLAYER
    - PRIMED_TNT
    - SHULKER_BULLET
    - THROWN_EXP_BOTTLE
    - TIPPED_ARROW
    - UNKNOWN
    - WEATHER
    - WITHER_SKULL
    - ARROW
    - BOAT
    - SPLASH_POTION
    - SMALL_FIREBALL
    - ENDER_DRAGON
  Unsafe_potion_effects:
    - WITHER
    - HEAL
  Unsafe_materials:
    - ACACIA_DOOR
    - BEDROCK
    - AIR
    - BED_BLOCK
    - BEEDROOT_BLOCK
    - BIRCH_DOOR
    - BREWING_STAND
    - BURNING_FURNACE
    - CAVE_BLOCK
    - CARROT
    - COMMAND
    - CAULDRON
    - COMMAND_CHAIN
    - COMMAND_REPEATING
    - COMMAND_MINECART
    - DARK_OAK_DOOR
    - DAYLIGHT_DETECTOR_INVERTED
    - DIODE_BLOCK_ON
    - DIODE_BLOCK_OFF
    - DOUBLE_PLANT
    - DOUBLE_STONE_SLAB2
    - EMPTY_MAP
    - ENDER_PORTAL
    - ENDER_PORTAL_FRAME
    - FIREWORK_CHARGE
    - FLOWER_POT
    - HUGE_MUSHROOM_1
    - HUGE_MUSHROOM_2
    - IRON_DOOR_BLOCK
    - JUNGLE_DOOR
    - KNOWLEDGE_BOOK
    - MONSTER_EGG
    - MONSTER_EGGS
    - PISTON_BASE
    - PISTON_EXTENSION
    - PISTON_MOVING_PIECE
    - PISTON_STICKY_BASE
    - REDSTONE_COMPARATOR_OFF
    - REDSTONE_LAMP_ON
    - REDSTONE_TORCH_OFF
    - SIGN_POST
    - SKULL
    - SKULL_ITEM
    - SNOW
    - SPRUCE_DOOR
    - SUGAR_CANE_BLOCK
    - STRUCTURE_BLOCK
    - STRUCTURE_VOID
    - STANDING_BANNER
    - STATIONARY_WATER
    - STATIONARY_LAVA
    - TIPPED_ARROW
    - TRIPWIRE
    - WALL_BANNER
    - WALL_SIGN
    - WATER
    - WATER_LILY
    - LAVA
    - WRITTEN_BOOK
    - POTATO