name: Genie
author: AuroraLS3
main: com.djrapitops.genie.Genie
version: 1.3.0
api-version: 1.16

commands:
    genie:
        usage: /genie [subcommand]
        description: Base command for genie admin commands.
        
permissions:
    genie.admin:
        default: op
        description: Access the '/genie' admin command