name: Genie
author: Rsl1122
main: com.djrapitops.genie.Genie
version: 1.2.1

commands:
    genie:
        usage: /genie [subcommand]
        description: Base command for genie admin commands.
        
permissions:
    genie.admin:
        default: op
        description: Access the '/genie' admin command